name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit app
        run: curl -I --max-redirs 5 https://queenshead-charity-golf-day-2026-mobile.streamlit.app/
